name: ğŸ Generate Snake Contribution Grid

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-generate
        with:
          github_user_name: ShaikhEamin
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: actions/upload-artifact@v4
        with:
          name: contribution-grid
          path: dist/github-contribution-grid-snake.svg
